apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cert-manager
  - cluster-issuer-staging.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.19.4
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values-dev.yaml