apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-stg

resources:
  - ../../base

replicas:
  - name: frontend
    count: 2

images:
  - name: 438950223046.dkr.ecr.eu-central-1.amazonaws.com/dev-myapp-frontend
    newName: 438950223046.dkr.ecr.eu-central-1.amazonaws.com/stg-myapp-frontend
    newTag: v0.0.0
