# ingress.yaml
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'        # ← HTTP → HTTPS redirect
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:438950223046:certificate/0890d942-56da-41cb-b91e-f9d3f0846e20

    external-dns.alpha.kubernetes.io/hostname: dev.bzyk0945.site

spec:
  ingressClassName: alb
  rules:
    - host: dev.bzyk0945.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80