apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  # <-- DWA poziomy w górę, do katalogu 'backend/base'

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: myapp # Upewnij się, że w base/deployment.yaml nazwa to 'backend'