apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - ../../../base/aws-load-balancer-controller

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 3.1.0
    releaseName: aws-load-balancer-controller
    namespace: kube-system
    valuesFile: values-dev.yaml