provider: aws
aws:
  region: eu-central-1

domainFilters:
  - bzyk0945.site

txtOwnerId: myapp

serviceAccount:
  name: external-dns        # ← musi być "external-dns" żeby pasowało do Pod Identity
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::438950223046:role/dev-external-dns