name: Frontend Production Pipeline

on:
  push:
    branches: [ "main", "test" ]
    paths: [ "02-app-source-code/frontend/**" ]
  workflow_dispatch:
    # Opcjonalnie: Możesz dodać parametry wejściowe (inputs)
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false

permissions:
  id-token: write   
  contents: read    
  # security-events: write

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: test
  # IAM_ROLE_ARN: arn:aws:iam::123456789012:role/GitHubActionRole

jobs:
  # integration:
  #   name: Quality Gate
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./02-app-source-code/frontend

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v6

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #         cache-dependency-path: frontend/package-lock.json

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Lint Code
  #       run: npm run lint

  #     - name: Run Unit Tests
  #       run: npm test -- --watchAll=false --passWithNoTests

  #     # Scans node_modules for vulnerabilities
  #     - name: Scan Dependencies (Trivy)
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: 'fs'
  #         scan-ref: './frontend'
  #         severity: 'CRITICAL,HIGH'
  #         ignore-unfixed: true
  #         exit-code: '1' # Fails pipeline if critical bugs found

  # JOB 2: BUILD & PUSH (Docker)
  delivery:
    name: Build & Push
    # needs: integration # Waits for Job 1 to pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # - name: Configure AWS Credentials (OIDC)
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ env.IAM_ROLE_ARN }}
      #     aws-region: ${{ env.AWS_REGION }}


      - name: Configure AWS Credentials (TEST)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and export to Docker so we can scan the image
      - name: Build and Load
        uses: docker/build-push-action@v6
        with:
          context: ./02-app-source-code/frontend
          load: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Scans the actual Docker image OS (Alpine/Debian)
      - name: Scan Docker Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # Push to AWS ECR only if scanning passes
      - name: Push to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./02-app-source-code/frontend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max